import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  requirementsSidebar: [{
    type: "autogenerated",
    dirName: "Requirements"
  }],
  designSidebar: [{
    type: "autogenerated",
    dirName: "Design"
  }]
};

export default sidebars;
