import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  requirementsSidebar: [{ type: "autogenerated", dirName: "Requirements" }],
};

export default sidebars;
